### PR TITLE
iPhone X support

### PR DESCRIPTION
**Pull request by eduarenas**
@mmccann34 - review

I had to fork MMDrawerController and host a version of the pod in our private spec repo. This uses the safe area api to fix a number of issues we had been seeing.

simulator screen shot - iphone x - 2017-11-13 at 15 24 59
simulator screen shot - iphone x - 2017-11-13 at 15 25 02
simulator screen shot - iphone x - 2017-11-13 at 15 25 05
simulator screen shot - iphone x - 2017-11-13 at 15 25 06
simulator screen shot - iphone x - 2017-11-13 at 15 25 10
simulator screen shot - iphone x - 2017-11-13 at 15 25 26
simulator screen shot - iphone x - 2017-11-13 at 15 25 28

### CODE REVIEW

**Comment by eduarenas** [comment]
https://app.clubhouse.io/gamechangermedia/story/35841/team-view-add-safe-area-to-the-top-of-a-team-view

**Comment by eduarenas** [comment]
https://app.clubhouse.io/gamechangermedia/story/35829/player-stats-add-safe-area-to-the-top-of-player-pages

**Comment by eduarenas** [comment]
https://app.clubhouse.io/gamechangermedia/story/35830/messaging-add-safe-area-to-the-top-and-bottom-of-a-message-view

(this fixes just the top)

**Comment by eduarenas** [comment]
https://app.clubhouse.io/gamechangermedia/story/35836/messaging-add-safe-area-to-the-top-of-the-message-read-screen

**Comment by eduarenas** [comment]
https://app.clubhouse.io/gamechangermedia/story/35839/team-list-add-safe-area-to-the-top-of-the-team-list

**Review by mmccann34 — APPROVED** [review]
nice 🐺

**Pull request merged**
